handling existing bucket error

diff --git a/uploadfile b/uploadfile
--- a/uploadfile
+++ b/uploadfile
@@ -9,7 +9,7 @@ else
     exit 1
 fi
 
-# listing existing s3 buckets
+# getting existing s3 buckets
 bucket_list=$(aws s3 ls | awk '{print $3}')
 
 # pushing buckets into an iterable list
@@ -26,28 +26,48 @@ select opt in "${options[@]}"
 do
     case $opt in
         "Use existing bucket")
-        echo "Using existing bucket"
-        # list s3 buckets present in users aws account
-        for i in "${buckets[@]}"
-        do  
-            echo $i
-        done
-        read -p "Choose existing bucket to use from the list of buckets which are present in your AWS account above: " existing_bucket
-        echo "Uploading file to $existing_bucket ...."
-        aws s3 cp "$file" "s3://$existing_bucket/$file"
-        break
-        ;;
+            echo "Using existing bucket"
+            # list s3 buckets present in users aws account
+            for i in "${buckets[@]}"
+            do  
+                echo $i
+            done
+            read -p "Choose existing bucket to use from the list of buckets which are present in your AWS account above: " existing_bucket
+            echo "Uploading file to $existing_bucket ...."
+            aws s3 cp "$file" "s3://$existing_bucket/$file"
+            break
+            ;;
         "Create new bucket")
-        read -p "Enter name of new bucket: " new_bucket
-        echo "Creating a new bucket called $new_bucket"
-        aws s3 mb s3://"$new_bucket"
-        ;;        
-        *) break
+            read -p "Enter name of new bucket: " new_bucket
+            echo "Creating a new bucket called $new_bucket ..."
+            create_bucket_output=$(aws s3 mb s3://"$new_bucket" 2>&1)
+            create_bucket_status=$?
+
+            if [[ $create_bucket_status -eq 0 ]]; then
+                echo "Bucket created successfully"
+            else    
+            # Handle specific error cases
+                if [[ "$create_bucket_output" == *"BucketAlreadyOwnedByYou"* ]]; then
+                    echo "Bucket $new_bucket already exists and is owned by you."
+                elif [[ "$create_bucket_output" == *"BucketAlreadyExists"* ]]; then
+                    echo "Bucket $new_bucket already exists, and it might be owned by someone else."
+                else    
+                    echo "An unexpected error occurred: $create_bucket_output"
+                    exit 1
+                fi
+            fi
+            # Uploading file to new bucket
+            echo "Uploading file to $new_bucket"
+            aws s3 cp "$file" "s3://$new_bucket/$file"
+            echo "File Uploaded Successfully"
+            break
+            ;;   
+        "Abort")
+            echo "Aborting the operation."
+            exit 0
+            ;;     
+        *) 
+            echo "Invalid option"
+            ;;
     esac
 done
-
-# conditional loop
-
-# if [[ $choice]]
-# prompt user to choose s3 bucket of choice
-# read -p "Which s3 bucket would you like to upload the file to?" bucket
